now: tp6

tp1:
	pdflatex tp1.tex
tp2:
	pdflatex tp2.tex
tp3:
	pdflatex tp3.tex
tp4:
	pdflatex tp4.tex
tp5:
	pdflatex tp5.tex
tp6:
	pdflatex tp6.tex
devoir1:
	pdflatex devoir1.tex
all: tp1 tp2 tp3 tp4 tp5 tp6 devoir1

.PHONY : clean
clean :
	rm -f *.aux *.log
	rm -f *.blg *.bbl
	rm -f *.toc
	rm -f *.tdo
	#rm -f *.pdf
	rm -f *.bcf
	rm -f *.brf
	rm -f *.out
	rm -f *.run.xml

